compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.0.2.cjs

npmAuditIgnoreAdvisories:
  - 'uuid (deprecation)'
  - '@types/helmet (deprecation)'
  - 'csurf (deprecation)'
