nodeLinker: pnp
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
cacheFolder: "/opt/.yarn/cache"
deferredVersionFolder: "/opt/.yarn/versions"
enableGlobalCache: true
globalFolder: "/opt/.yarn/berry/global"