name: apple-frontend
apiVersion: v2
home: https://github.com/hmcts/cnp-plum-frontend
version: 0.1.4
description: HMCTS apple frontend application (test application)
maintainers:
  - name: HMCTS Platform Engineering Team
dependencies:
  - name: nodejs
    version: 2.3.5
    repository: "https://hmctspublic.azurecr.io/helm/v1/repo/"
annotations:
  kubernetes.io/ingress.class: traefik
  traefik.ingress.kubernetes.io/router.tls: "true"