nodejs:
  applicationPort: 1337
  image: 'sdshmctspublic.azurecr.io/apple/frontend:latest'
  aadIdentityName: apple
  ingressHost: toffee-recipe-backend.{{ .Values.global.environment }}.platform.hmcts.net
  environment:
    RECIPE_BACKEND_URL: http://toffee-recipe-backend.{{ .Values.global.environment }}.platform.hmcts.net
  keyVaults:
    'applesi':
      secrets:
        - name: appInsights-InstrumentationKey
