apiVersion: v2
appVersion: '1.0'
description: A Helm chart for toffee-frontend App
name: toffee-frontend
home: https://github.com/hmcts/toffee-frontend
version: 0.0.3
dependencies:
  - name: nodejs
    version: 2.4.15
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
