nodejs:
  applicationPort: 1337
  image: 'sdshmctspublic.azurecr.io/toffee/frontend:latest'
  aadIdentityName: toffee
  environment:
    RECIPE_BACKEND_URL: http://plum-recipe-backend-java
  keyVaults:
    "toffeesi":
      secrets:
        - name: appInsights-InstrumentationKey
