nodejs:
  applicationPort: 1337
  image: 'sdshmctsprivate.azurecr.io/toffee/frontend:ek-test-4'
  aadIdentityName: toffee
  environment:
    RECIPE_BACKEND_URL: http://plum-recipe-backend-java
  keyVaults:
    "toffeesi":
      secrets:
        - name: appInsights-InstrumentationKey
