nodejs:
  applicationPort: 1337
  image: 'sdshmctspublic.azurecr.io/toffee/frontend:latest'
  aadIdentityName: toffee
  ingressHost: toffee-recipe-backend.{{ .Values.global.environment }}.platform.hmcts.net
  environment:
    RECIPE_BACKEND_URL: http://toffee-recipe-backend.{{ .Values.global.environment }}.platform.hmcts.net
  keyVaults:
    'toffeesi':
      secrets:
        - name: appInsights-InstrumentationKey
